# Generated by Django 4.1.1 on 2022-12-05 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0002_remove_account_appname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='ImageFile',
            field=models.ImageField(blank=True, null=True, upload_to='User'),
        ),
    ]
