# Generated by Django 4.1.1 on 2022-12-05 22:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Account', '0003_alter_account_imagefile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='UserAccount',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='UserSpecification', to=settings.AUTH_USER_MODEL),
        ),
    ]
