# Generated by Django 4.1.1 on 2022-12-10 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0004_alter_account_useraccount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='ImageFile',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='User'),
        ),
    ]
