# Generated by Django 4.1.1 on 2022-12-03 03:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=150)),
                ('Image', models.ImageField(blank=True, null=True, upload_to='Procuts')),
                ('Price', models.IntegerField()),
                ('Reviews', models.IntegerField()),
                ('Rate', models.IntegerField()),
                ('Categories', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AmazonProducts.category')),
            ],
        ),
    ]
