# Generated by Django 4.1.1 on 2022-12-04 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AmazonProducts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='Price',
            field=models.CharField(max_length=150),
        ),
    ]
