# Generated by Django 4.1.1 on 2022-12-04 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AmazonProducts', '0002_alter_products_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='Rate',
            field=models.CharField(max_length=150),
        ),
    ]
