# Generated by Django 4.1.1 on 2022-12-04 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AmazonProducts', '0003_alter_products_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='Reviews',
            field=models.CharField(max_length=150),
        ),
    ]
