# Generated by Django 4.1.1 on 2022-12-04 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AmazonProducts', '0004_alter_products_reviews'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='Image',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
